# Generated by Django 5.2.4 on 2025-07-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientprofile_developerprofile_jwttokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.DeleteModel(
            name='JwtTokens',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
